In [61]:
print("Hello World")

Hello World


## Functions, Conditionals, and Iteration
Let's create a Python function, and call it from a loop.

In [62]:
def HelloWorldXY(x, y):
    if x < 10:
        print("Hello World, x was < 10")
    elif x < 20:
        print("Hello World, x was >= 10 but < 20")
    else:
        print("Hello World, x was >= 20")
    return x + y


for i in range(8, 25, 5):  # i=8, 13, 18, 23 (start, stop, step)
    print("--- Now running with i: {}".format(i))
    r = HelloWorldXY(i, i)
    print("Result from HelloWorld: {}".format(r))

--- Now running with i: 8
Hello World, x was < 10
Result from HelloWorld: 16
--- Now running with i: 13
Hello World, x was >= 10 but < 20
Result from HelloWorld: 26
--- Now running with i: 18
Hello World, x was >= 10 but < 20
Result from HelloWorld: 36
--- Now running with i: 23
Hello World, x was >= 20
Result from HelloWorld: 46


In [63]:
print(HelloWorldXY(1, 2))

Hello World, x was < 10
3


In [64]:
print("Iterate over the items. `range(2)` is like a list [0,1].")
for i in range(2):
    print(i)

print("Iterate over an actual list.")
for i in [0, 1]:
    print(i)

print("While works")
i = 0
while i < 2:
    print(i)
    i += 1

Iterate over the items. `range(2)` is like a list [0,1].
0
1
Iterate over an actual list.
0
1
While works
0
1


In [65]:
print("Python supports standard key words like continue and break")
while True:
    print("Entered while")
    break

Python supports standard key words like continue and break
Entered while


## Numpy and lists

In [66]:
import numpy as np  # Make numpy available using np.

# Create a numpy array, and append an element
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
    print(i)

print("\nPrinting each element and their index")
for i, e in enumerate(a):
    print("Index: {}, was: {}".format(i, e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [67]:
print("\nShowing some basic math on arrays")
b = np.array([0, 1, 4, 3, 2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


In [68]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int32'>


In [69]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[0.89687683 0.9197779  0.82291042]
 [0.20267739 0.01177698 0.79146272]
 [0.88843022 0.12586202 0.01068118]]


In [70]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))
print("...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists")


You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)
...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists


## Colab Specifics

Colab is a virtual machine you can access directly. To run commands at the VM's terminal, prefix the line with an exclamation point (!).


In [71]:
print(
    "Install numpy"
)  # Just for test, numpy is actually preinstalled in all Colab instances
# !pip install numpy

Install numpy


In [72]:
import tensorflow as tf

gpus = tf.config.list_physical_devices("GPU")
tf.test.is_gpu_available()
gpu_count = len(gpus)

print("Number of available GPUs:", gpu_count)

Number of available GPUs: 1
